# Generated by Django 3.2.12 on 2022-04-24 18:13

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220404_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='text_record',
            field=models.FileField(default=0, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='records'),
            preserve_default=False,
        ),
    ]
